Add a gmcp.player message
sneezymud/sneezymud pull request #237
Opened 2019-10-02 15:54 UTC by dericpr

currently only sends the players level on startup and whenever the player gains a level

2021-03-16 01:38 UTC, wershlak commented
@dericpr @cizra Anyone able to test this now and vouch for it?

2021-03-16 10:18 UTC, cizra commented
@wershlak there's a bunch of unresolved feedback

2021-03-16 10:18 UTC, cizra requested changes

2023-01-28 05:52 UTC, drewhershey commented
Closing this PR out as well, as it's several years old and simple enough that it could easily be reopened and completed if desired.

2023-01-28 05:52 UTC, closed without merging