Lightning bolt weapon proc
sneezymud/sneezymud pull request #345
Opened 2021-06-22 02:37 UTC by Durhamite2118

Similar to molten/glacial except lightning / electric damage based

2021-06-22 05:26 UTC, cizra requested changes

2021-06-22 05:26 UTC, cizra commented on code/code/spec/spec_objs_weapons.cc
> +// Summary of this weapon proc
indent missing

2021-06-22 05:26 UTC, cizra commented on code/code/spec/spec_objs_weapons.cc
> +if (!vict->limbConnections(j)) {
Is this file mostly copy-paste? Maybe we could consolidate the code with bonebreak or lightsaber or such, passing in the specific flavor strings and chances and whatnot?

2021-06-23 01:53 UTC, wershlak requested changes

2021-06-23 01:53 UTC, wershlak commented on code/code/spec/spec_objs_weapons.cc
> +  act(buf, FALSE, ch, o, vict, TO_VICT, ANSI_GREY);
https://github.com/sneezymud/sneezymud/blob/master/code/code/sys/ansi.h#L93-L114

There's no ANSI_GREY

Simple mistake but I think you need to be able to build and test your changes locally if you want to be able to contribute. I usually would compile a thing like this change and ensure the proc fires and does what I think it should, doesn't crash the mud and all the ansi looks pretty. Once, you get a local instance running it's not too much work to run a short test on each change.

@cizra's instructions here worked great: https://github.com/sneezymud/sneezymud-docker#to-develop-using-a-clean-database

2021-06-23 01:53 UTC, wershlak commented on code/code/spec/spec_objs.cc
> -extern int glacialWeapon(TBeing *vict, cmdTypeT cmd, const char *arg, TObj *o, TObj *);
Why'd you delete this? That's not right

2021-06-23 01:53 UTC, wershlak commented on code/code/spec/spec_objs_weapons.cc
> +  if (vict->isImmune(IMMUNE_ELECTRIC, slot))
IMMUNE_ELECTRIC isn't a thing either.

2021-06-23 14:06 UTC, closed without merging